grpc:
  server:
    port: 0


collector:
  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      topic: "stats.user-actions.v1"
      properties:
        key.serializer: "org.apache.kafka.common.serialization.LongSerializer"
        value.serializer: "serializer.GeneralAvroSerializer"